### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by GoogleMike** [esperancaleonardo/LIA_Deep_Q_Learning#2]
Hello, I am currently doing a job similar to yours.
Could you please give me a tutorial that shows how to use it?
It seems that  DQN.py needs some arguments to work well.
When I type 

> python DQN.py 0 2000

**TypeError: argument 1 must be read-only bytes-like object, not array.array**

Then 
> python DQN.py 1 2000

**Unable to open file (unable to open file: name = 'model_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)**

Could you please help me?
Thank you very much.

**Comment by esperancaleonardo** [comment]
Hi, 

i'm currently not giving any support for this rep and I discourage you using that. The code in this rep uses the old python API for VREP, an old and slow API for RL works. This was a first approach with vrep.

I suggest you to take a look at my currently WIP on my other repository dqn_pyrep_lia, that uses a fresh new API for pyrep and RL tasks.

[my rep](https://github.com/esperancaleonardo/dqn_pyrep_lia)
[pyrep's rep](https://github.com/stepjam/PyRep)
